"""

"""

from talon.voice import Context, Key

ctx = Context("words")
ctx.keymap(
    {
        "snippet console": "cl`",
        "snippet log": "log`",
        "snippet spooky": "spooky`",
        "dot company": ".com",
        "word parse integer": ["parseInt()", Key("left")],
        "word and": "end",
        "word a sink": "async",
        "word acxiom": "axios",
        "word adam": "atom",
        "word cape": "kapyra",
        "word cmd": "cmd",
        "word cycling": "cyclom",
        "word define": "def ",
        "word (dickt | dictionary)": "dict",
        "word doctor": "docker",
        "word dup": "dup",
        "word eye": "eye",
        "word for each": "forEach",
        "word import": "import ",
        "word iter": "iter",
        "word display in line": "display: inline-block;",
        "word display block": "display: block;",
        "word get": "git",
        "word get hub": "github",
        "word glitch": "glitch",
        "word just": "gist",
        "word hand": "hand",
        "(name|word) hero": "heroku",
        "word jason": "JSON",
        "word mongo": "mongo",
        "word no": "null",
        "word no super": "NULL",
        "word node": "node",
        "word nodemon": "nodemon",
        "word pixel": "pixel",
        "word plank": "planck",
        "word postgres": "postgres",
        "word printf": "printf",
        "word queue": "queue",
        "word ramda": "ramda",
        "word (sql|sequel)": "sequelize",
        "word shell": "shell",
        "word slack": "slack",
        "word ping": "ping ",
        "word pseudo": "sudo ",
        "word talon": "talon",
        "word them": "vim",
        "word two strings": "toString",
        "word while": "while",
        "word will": "twilio",
        "word with": "width",
        "word while": "wow",
        "word zeppelin": "zeplin",
    }
)
